#ESCREVA UM PROGRAMA QUE FAÇA O COMPUTADPR 'PENSAR' EM UM NÚMERO INTEIRO
#ENTRE 0 E 5 E PEÇA PARA O USUÁRIO TENTAR DESCOBRIR QUAL FOI O NÚMERO ESCOLHIDO
#O PROGRAMA DEVERÁ ESCREVER NA TELA SE O USUÁRIO VENCEU OU PERDEU.